ProSoft.UI/Areas/Shared/Controllers/ClassificationCustController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProSoft.Core.Repositories.Medical.HospitalPatData;
using ProSoft.EF.DTOs.Medical.HospitalPatData;
using ProSoft.EF.DTOs.Stocks;
using ProSoft.EF.IRepositories.Medical.HospitalPatData;
using ProSoft.EF.IRepositories.Stocks;
using ProSoft.EF.Models.Medical.HospitalPatData;

namespace ProSoft.UI.Areas.Shared.Controllers
{
    [Authorize]
    [Area("Shared")]
    public class ClassificationCustController : Controller
    {
        private readonly IClassificationCustRepo _classCustRepo;
        private readonly IMapper _mapper;
        public ClassificationCustController(IClassificationCustRepo classCustRepo, IMapper mapper)
        {
            _classCustRepo = classCustRepo;
            _mapper = mapper;
        }

        /// Get GetSubComp
        public async Task<IActionResult> GetDepartments()
        {
            List<ClassificationCust> departments = await _classCustRepo.GetAllAsync();
            return Json(departments);
        }
        public async Task<IActionResult> Index()
        {
            List<ClassificationCust> departments = await _classCustRepo.GetAllAsync();
            List<ClassificationViewDTO> departmentsDTO = _mapper.Map<List<ClassificationViewDTO>>(departments);
            return View(departmentsDTO);
        }

        // Get Add
        public async Task<IActionResult> Add_ClassCust()
        {
            ViewBag.departId = await _classCustRepo.GetNewIdAsync();
            return View();
        }

        // Post Add
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add_ClassCust(ClassificationViewDTO classCastDTO)
        {
            if (ModelState.IsValid)
            {
                ClassificationCust classCast = _mapper.Map<ClassificationCust>(classCastDTO);

                await _classCustRepo.AddAsync(classCast);
                await _classCustRepo.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(classCastDTO);
        }

        // Get Edit
        public async Task<IActionResult> Edit_ClassCust(int id)
        {
            ClassificationCust classCast = await _classCustRepo.GetByIdAsync(id);
            ClassificationViewDTO classCastDTO = _mapper.Map<ClassificationViewDTO>(classCast);
            return View(classCastDTO);
        }

        // Post Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit_ClassCust(int id, ClassificationViewDTO classCastDTO)
        {
            if (ModelState.IsValid)
            {
                ClassificationCust classCast = await _classCustRepo.GetByIdAsync(id);
                _mapper.Map(classCastDTO, classCast);

                await _classCustRepo.UpdateAsync(classCast);
                await _classCustRepo.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(classCastDTO);
        }

        // Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete_ClassCust(int id)
        {
            ClassificationCust classCast = await _classCustRepo.GetByIdAsync(id);

            await _classCustRepo.DeleteAsync(classCast);
            await _classCustRepo.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

ProSoft.UI/Areas/Shared/Controllers/EisPostingController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProSoft.EF.DTOs.Accounts;
using ProSoft.EF.DTOs.Shared;
using ProSoft.EF.IRepositories.Shared;
using ProSoft.EF.Models.Shared;

namespace ProSoft.UI.Areas.Shared.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Shared")]
    public class EisPostingController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IEisPostingRepo _eisPostingRepo;
        public EisPostingController(IMapper mapper, IEisPostingRepo eisPostingRepo)
        {
            _mapper = mapper;
            _eisPostingRepo = eisPostingRepo;
        }

        public async Task<IActionResult> Index()
        {
            List<EisPostingViewDTO> eisPostings = await _eisPostingRepo.GetAllCodesAsync();
            return View(eisPostings);
        }

        public async Task<IActionResult> GetSubCodesFor(string id)
        {
            List<AccSubCodeDTO> subCodesDTO = await _eisPostingRepo.GetSubCodesForAsync(id);
            return Json(subCodesDTO);
        }

        // Get Add
        public async Task<IActionResult> Add_SysAccount()
        {
            EisPostingEditAddDTO eisPostingDTO = await _eisPostingRepo.GetEmptyEisPostingAsync();
            return View(eisPostingDTO);
        }

        // Post Add
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add_SysAccount(EisPostingEditAddDTO eisPostingDTO)
        {
            if (ModelState.IsValid)
            {
                EisPosting eisPosting = _mapper.Map<EisPosting>(eisPostingDTO);
                eisPosting.BranchId = int.Parse(User.Claims.FirstOrDefault(c => c.Type == "U_Branch_Id").Value);

                await _eisPostingRepo.AddAsync(eisPosting);
                await _eisPostingRepo.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(eisPostingDTO);
        }

        // Get Edit
        public async Task<IActionResult> Edit_SysAccount(int id)
        {
            EisPostingEditAddDTO eisPostingDTO = await _eisPostingRepo.GetEisPostingByIdAsync(id);
            return View(eisPostingDTO);
        }

        // Post Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit_SysAccount(int id, EisPostingEditAddDTO eisPostingDTO)
        {
            if (ModelState.IsValid)
            {
                EisPosting eisPosting = await _eisPostingRepo.GetByIdAsync(id);
                _mapper.Map(eisPostingDTO, eisPosting);
                eisPosting.PostId = id;

                await _eisPostingRepo.UpdateAsync(eisPosting);
                await _eisPostingRepo.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(eisPostingDTO);
        }

        // Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete_SysAccount(int id)
        {
            EisPosting eisPosting = await _eisPostingRepo.GetByIdAsync(id);

            await _eisPostingRepo.DeleteAsync(eisPosting);
            await _eisPostingRepo.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

ProSoft.UI/Areas/Stocks/Controllers/MainItemController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProSoft.EF.DTOs.Accounts;
using ProSoft.EF.DTOs.Stocks;
using ProSoft.EF.IRepositories.Accounts;
using ProSoft.EF.IRepositories.Stocks;
using ProSoft.EF.Models.Accounts;
using ProSoft.EF.Models.Stocks;

namespace ProSoft.UI.Areas.Stocks.Controllers
{
    [Authorize]
    [Area(nameof(Stocks))]
    public class MainItemController : Controller
    {
        private readonly IMainItemRepo _mainItemRepo;
        private readonly ICostCenterRepo _costCenterRepo;
        private readonly IStockTypeRepo _stockTypeRepo;
        private readonly IMapper _mapper;
        private readonly IStockRepo _stockRepo;
        public MainItemController(IMainItemRepo mainItemRepo, ICostCenterRepo costCenterRepo,
            IStockTypeRepo stockTypeRepo, IMapper mapper, IStockRepo stockRepo)
        {
            _mainItemRepo = mainItemRepo;
            _costCenterRepo = costCenterRepo;
            _stockTypeRepo = stockTypeRepo;
            _mapper = mapper;
            _stockRepo = stockRepo;
        }

        public async Task<IActionResult> ChooseStockType()
        {
            List<KindStore> stockTypes = await _stockTypeRepo.GetAllAsync();
            var stockTypesDTO = _mapper.Map<List<KindStoreDTO>>(stockTypes);
            return View(stockTypesDTO);
        }

        //Get AddStock
        public async Task<IActionResult> AddStocksToGroup(int id, int flag1)
        {
            MainItemStockDTO mainItemStockDTO = await _mainItemRepo.GetNewMainItemStockAsync(id);
            #region sidebar
            ViewBag.MainLevel_2 = await _mainItemRepo.GetMainItemsByLevelAsync(2, flag1);
            ViewBag.MainLevel_3 = await _mainItemRepo.GetMainItemsByLevelAsync(3, flag1);
            ViewBag.MainLevel_4 = await _mainItemRepo.GetMainItemsByLevelAsync(4, flag1);
            ViewBag.MainLevel_5 = await _mainItemRepo.GetMainItemsByLevelAsync(5, flag1);
            ViewBag.MainLevel_6 = await _mainItemRepo.GetMainItemsByLevelAsync(6, flag1);
            #endregion
            return View(mainItemStockDTO);
        }

        //Post AddStock
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddStocksToGroup(int id, int[] stocks, MainItemStockDTO mainItemStockDTO)
        {
            if (ModelState.IsValid)
            {
                await _mainItemRepo.UpdateStocksForGroupAsync(id, stocks);
                return RedirectToAction(mainItemStockDTO.MainLevel, new { id = mainItemStockDTO.ParentCode, flag1 = mainItemStockDTO.Flag1 });
            }
            #region sidebar
            ViewBag.MainLevel_2 = await _mainItemRepo.GetMainItemsByLevelAsync(2, (int)mainItemStockDTO.Flag1);
            ViewBag.MainLevel_3 = await _mainItemRepo.GetMainItemsByLevelAsync(3, (int)mainItemStockDTO.Flag1);
            ViewBag.MainLevel_4 = await _mainItemRepo.GetMainItemsByLevelAsync(4, (int)mainItemStockDTO.Flag1);
            ViewBag.MainLevel_5 = await _mainItemRepo.GetMainItemsByLevelAsync(5, (int)mainItemStockDTO.Flag1);
            ViewBag.MainLevel_6 = await _mainItemRepo.GetMainItemsByLevelAsync(6, (int)mainItemStockDTO.Flag1);
            #endregion
            MainItemStockDTO newMainItemStockDTO = await _mainItemRepo.GetNewMainItemStockAsync(id);
            _mapper.Map(newMainItemStockDTO, mainItemStockDTO);
            return View(mainItemStockDTO);
        }

        ///////////////////////////////////////////////////////
        // Main Level 2

        public async Task<IActionResult> MainLevel_2(int flag1)
        {
            if (flag1 == 0)
                return RedirectToAction(nameof(ChooseStockType));
            List<MainItemViewDTO> mainLevel_2 = await _mainItemRepo.GetMainItemsByLevelAsync(2, flag1);
            KindStore stockType = await _stockTypeRepo.GetByIdAsync(flag1);
            ViewBag.stockType = stockType.KName;
            #region sidebar
            ViewBag.MainLevel_2 = await _mainItemRepo.GetMainItemsByLevelAsync(2, flag1);
            ViewBag.MainLevel_3 = await _mainItemRepo.GetMainItemsByLevelAsync(3, flag1);
            ViewBag.MainLevel_4 = await _mainItemRepo.GetMainItemsByLevelAsync(4, flag1);
            ViewBag.MainLevel_5 = await _mainItemRepo.GetMainItemsByLevelAsync(5, flag1);
            ViewBag.MainLevel_6 = await _mainItemRepo.GetMainItemsByLevelAsync(6, flag1);
            #endregion
            return View(mainLevel_2);
        }

        //Get Add
        public async Task<IActionResult> Add_MainLevel_2(int flag1)
        {
            MainItemEditAddDTO newMainLevel_2 = await _mainItemRepo.GetNewMainLevel_2_Async(flag1);
            KindStore stockType = await _stockTypeRepo.GetByIdAsync(flag1);
            ViewBag.stockType = stockType.KName;
            #region sidebar
            ViewBag.MainLevel_2 = await _mainItemRepo.GetMainItemsByLevelAsync(2, flag1);
            ViewBag.MainLevel_3 = await _mainItemRepo.GetMainItemsByLevelAsync(3, flag1);
            ViewBag.MainLevel_4 = await _mainItemRepo.GetMainItemsByLevelAsync(4, flag1);
            ViewBag.MainLevel_5 = await _mainItemRepo.GetMainItemsByLevelAsync(5, flag1);
            ViewBag.MainLevel_6 = await _mainItemRepo.GetMainItemsByLevelAsync(6, flag1);
            #endregion
            return View(newMainLevel_2);
        }

        //Post Add
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add_MainLevel_2(MainItemEditAddDTO mainItemDTO)
        {
            if (ModelState.IsValid)
            {
                mainItemDTO.BranchId = int.Parse(User.Claims.FirstOrDefault(c => c.Type == "U_Branch_Id").Value);
                mainItemDTO.UserCode = int.Parse(User.Claims.FirstOrDefault(c => c.Type == "User_Code").Value);

                await _mainItemRepo.AddMainLevelAsync(mainItemDTO);
                return RedirectToAction(nameof(MainLevel_2), new { flag1 = mainItemDTO.Flag1 } );
            }
            KindStore stockType = await _stockTypeRepo.GetByIdAsync((int)mainItemDTO.Flag1);
            ViewBag.stockType = stockType.KName;
            #region sidebar
            ViewBag.MainLevel_2 = await _mainItemRepo.GetMainItemsByLevelAsync(2, (int)mainItemDTO.Flag1);
            ViewBag.MainLevel_3 = await _mainItemRepo.GetMainItemsByLevelAsync(3, (int)mainItemDTO.Flag1);
            ViewBag.MainLevel_4 = await _mainItemRepo.GetMainItemsByLevelAsync(4, (int)mainItemDTO.Flag1);
            ViewBag.MainLevel_5 = await _mainItemRepo.GetMainItemsByLevelAsync(5, (int)mainItemDTO.Flag1);
            ViewBag.MainLevel_6 = await _mainItemRepo.GetMainItemsByLevelAsync(6, (int)mainItemDTO.Flag1);
            #endregion
            MainItemEditAddDTO mainLevel_2 = await _mainItemRepo.GetNewMainLevel_2_Async((int)mainItemDTO.Flag1);
            _mapper.Map(mainLevel_2, mainItemDTO);
            return View(mainItemDTO);
        }

        //Get Edit
        public async Task<IActionResult> Edit_MainLevel_2(int id)
        {
            MainItemEditAddDTO mainLevel_2 = await _mainItemRepo.GetMainLevelByIdAsync(id);
            KindStore stockType = await _stockTypeRepo.GetByIdAsync((int)mainLevel_2.Flag1);
            ViewBag.stockType = stockType.KName;
            #region sidebar
            ViewBag.MainLevel_2 = await _mainItemRepo.GetMainItemsByLevelAsync(2, (int)mainLevel_2.Flag1);
            ViewBag.MainLevel_3 = await _mainItemRepo.GetMainItemsByLevelAsync(3, (int)mainLevel_2.Flag1);
            ViewBag.MainLevel_4 = await _mainItemRepo.GetMainItemsByLevelAsync(4, (int)mainLevel_2.Flag1);
            ViewBag.MainLevel_5 = await _mainItemRepo.GetMainItemsByLevelAsync(5, (int)mainLevel_2.Flag1);
            ViewBag.MainLevel_6 = await _mainItemRepo.GetMainItemsByLevelAsync(6, (int)mainLevel_2.Flag1);
            #endregion
            return View(mainLevel_2);
        }

        //Post Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit_MainLevel_2(int id, MainItemEditAddDTO mainItemDTO)
        {
            if (ModelState.IsValid)
            {
                mainItemDTO.BranchId = int.Parse(User.Claims.FirstOrDefault(c => c.Type == "U_Branch_Id").Value);
                mainItemDTO.UserCode = int.Parse(User.Claims.FirstOrDefault(c => c.Type == "User_Code").Value);

                await _mainItemRepo.EditMainLevelAsync(id, mainItemDTO);
                return RedirectToAction(nameof(MainLevel_2), new { flag1 = mainItemDTO.Flag1 });
            }
            KindStore stockType = await _stockTypeRepo.GetByIdAsync((int)mainItemDTO.Flag1);
            ViewBag.stockType = stockType.KName;
            #region sidebar
            ViewBag.MainLevel_2 = await _mainItemRepo.GetMainItemsByLevelAsync(2, (int)mainItemDTO.Flag1);
            ViewBag.MainLevel_3 = await _mainItemRepo.GetMainItemsByLevelAsync(3, (int)mainItemDTO.Flag1);
            ViewBag.MainLevel_4 = await _mainItemRepo.GetMainItemsByLevelAsync(4, (int)mainItemDTO.Flag1);
            ViewBag.MainLevel_5 = await _mainItemRepo.GetMainItemsByLevelAsync(5, (int)mainItemDTO.Flag1);
            ViewBag.MainLevel_6 = await _mainItemRepo.GetMainItemsByLevelAsync(6, (int)mainItemDTO.Flag1);
            #endregion
            MainItemEditAddDTO mainLevel_2 = await _mainItemRepo.GetMainLevelByIdAsync(id);
            _mapper.Map(mainLevel_2, mainItemDTO);
            return View(mainItemDTO);
        }

        //Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete_MainLevel_2(int id)
        {
            MainItem mainItem = await _mainItemRepo.GetByIdAsync(id);

            await _mainItemRepo.DeleteAsync(mainItem);
            await _mainItemRepo.SaveChangesAsync();
            return RedirectToAction(nameof(MainLevel_2), new { flag1 = mainItem.Flag1 });
        }

        ///////////////////////////////////////////////////////
        // Main Level 3

ProSoft.UI/Areas/Stocks/Views/Shared/_LayoutItemsGuide.cshtml
@{
    List<MainItemViewDTO> GetMainLevel_3(string code) //function recieve maincode
    {
        string subString = code.Substring(0, 1);
        List<MainItemViewDTO> mainLevel_3 = (List<MainItemViewDTO>)ViewBag?.MainLevel_3;

        return mainLevel_3.Where(obj => obj.MainCode.Substring(0, 1) == subString).ToList();
    }
    List<MainItemViewDTO> GetMainLevel_4(string code)
    {
        string subString = code.Substring(0, 3);
        List<MainItemViewDTO> mainLevel_4 = (List<MainItemViewDTO>)ViewBag?.MainLevel_4;

        return mainLevel_4.Where(obj => obj.MainCode.Substring(0, 3) == subString).ToList();
    }
    List<MainItemViewDTO> GetMainLevel_5(string code)
    {
        string subString = code.Substring(0, 5);
        List<MainItemViewDTO> mainLevel_5 = (List<MainItemViewDTO>)ViewBag?.MainLevel_5;

        return mainLevel_5.Where(obj => obj.MainCode.Substring(0, 5) == subString).ToList();
    }
    List<MainItemViewDTO> GetMainLevel_6(string code)
    {
        string subString = code.Substring(0, 7);
        List<MainItemViewDTO> mainLevel_6 = (List<MainItemViewDTO>)ViewBag?.MainLevel_6;

        return mainLevel_6.Where(obj => obj.MainCode.Substring(0, 7) == subString).ToList();
    }
    
    string F_Year = User.Claims.FirstOrDefault(c => c.Type == "F_Year").Value;
    var isRTL = CultureInfo.CurrentCulture.Name.StartsWith("ar");
}
@inject IViewLocalizer localizer

<!DOCTYPE html>
<html lang="en" dir="@(isRTL ? "RTL" : "LTR")">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Items Guide</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/layout_MedAnalysis.css" asp-append-version="true" />
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
          integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />
</head>
<body>
    <div class="d-flex">
        <div id="mySidebar" class="col-2 bg-dark p-0">
            <div class="vh-100 p-1 d-flex flex-column">
                <a asp-area="Stocks" asp-controller="MainItem" asp-action="index" class="d-flex my-2 justify-content-center text-white text-decoration-none">
                    <span class="fs-3 d-sm-inline">@localizer["Items Guide"]</span>
                </a>
                <a asp-area="Stocks" asp-controller="MainItem" asp-action="MainLevel_2" onclick="openLevel(event)" class="d-flex my-2 justify-content-start ps-2 text-white text-decoration-none fs-4">
                    @localizer["The Items"]
                </a>
                <ul class="nav nav-pills flex-column p-0">
                    @foreach (var item in ViewBag?.MainLevel_2)
                    {
                    <li class="nav-item has-submenu">
                        <a asp-area="Stocks" asp-controller="MainItem" asp-action="MainLevel_3" asp-route-id="@item.MainCode" class="nav-link hover-link">
                            <i class="fa-solid fa-caret-@(isRTL ? "left ms-1" : "right me-1")"></i>
                            @item.MainName
                        </a>
                        <ul class="submenu collapse p-0">
                            @foreach (var sub in GetMainLevel_3(item.MainCode))
                            {
                            <li class="nav-item has-submenu">
                                <a asp-area="Stocks" asp-controller="MainItem" asp-action="MainLevel_4" asp-route-id="@sub.MainCode" class="nav-link hover-link @(isRTL ? "pe-4" : "ps-4")">
                                    <i class="fa-solid fa-caret-@(isRTL ? "left ms-1" : "right me-1")"></i>
                                    @sub.MainName
                                </a>
                                <ul class="submenu collapse p-0">
                                    @foreach (var subitem in GetMainLevel_4(sub.MainCode))
                                    {
                                    <li class="nav-item">
                                        <a asp-area="Stocks" asp-controller="MainItem" asp-action="MainLevel_5" asp-route-id="@subitem.MainCode" class="nav-link hover-link @(isRTL ? "me-2 pe-4" : "ms-2 ps-4")">
                                            <i class="fa-solid fa-caret-@(isRTL ? "left ms-1" : "right me-1")"></i>
                                            @subitem.MainName
                                        </a>
                                        <ul class="submenu collapse p-0">
                                            @foreach (var subSubitem in GetMainLevel_5(subitem.MainCode))
                                            {
                                            <li class="nav-item">
                                                <a asp-area="Stocks" asp-controller="MainItem" asp-action="MainLevel_6" asp-route-id="@subSubitem.MainCode" class="nav-link hover-link @(isRTL ? "me-3 pe-4" : "ms-3 ps-4")">
                                                    <i class="fa-solid fa-caret-@(isRTL ? "left ms-1" : "right me-1")"></i>
                                                    @subSubitem.MainName
                                                </a>
                                                <ul class="submenu collapse p-0">
                                                    @foreach (var lastitem in GetMainLevel_6(subSubitem.MainCode))
                                                    {
                                                    <li class="nav-item">
                                                        <a @* asp-area="Stocks" asp-controller="MainItem" asp-action="MainLevel_6" asp-route-id="@lastitem.MainCode" *@ class="nav-link hover-link @(isRTL ? "me-4 pe-4" : "ms-4 ps-4")">
                                                            @* <i class="fa-solid fa-caret-@(isRTL ? "left ms-1" : "right me-1")"></i> *@
                                                            @lastitem.MainName
                                                        </a>
                                                    </li>
                                                    }
                                                </ul>
                                            </li>
                                            }
                                        </ul>
                                    </li>
                                    }
                                </ul>
                            </li>
                            }
                        </ul>
                    </li>
                    }
                </ul>

            </div>
        </div>

        <div class="content pb-3 position-relative" style="flex: 1; ">
            <div class="d-flex justify-content-between align-items-center gap-2 p-2 shadow-sm rounded">
                <button class="toggler btn btn-secondary rounded-4" onclick="toggleNav()">☰</button>
                <a class="btn btn-secondary rounded-circle" href="/Home/Index" title="go to modules">
                    <i class="fa-solid fa-chevron-@(isRTL ? "right" : "left")"></i>
                </a>
                <span class="fw-bold text-capitalize">@User.Identity.Name</span>
                <span class="fw-bold">@F_Year</span>
                <div class="d-flex align-items-center gap-2 @(isRTL ? "me-auto" : "ms-auto")">
                    <partial name="_SelectLanguagePartial" />
                    <a asp-action="Logout" asp-controller="Account" class="btn btn-secondary">@localizer["Log out"]</a>
                </div>
            </div>
            @RenderBody()
        </div>

        @* Overlay for sidebar in small screen *@
        <div class="overlay position-absolute" onclick="toggleNav()"></div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/popup.js" asp-append-version="true"></script>
    <script type="text/javascript">
        function toggleNav() {
            const navBar = document.getElementById("mySidebar");
            navBar.classList.toggle("nav-open");

            const overlay = document.querySelector(".overlay");
            overlay.classList.toggle("lay-active");
        }

        function openLevel(e) {
            e.preventDefault();
            let flag1 = localStorage.getItem("flag1");
            let link = e.target;
            let action = `${link.getAttribute("href")}?flag1=${flag1}`;
            window.location.href = action;
        }

        // console.log(document.querySelectorAll("#mySidebar .nav-link"));
        document.addEventListener("DOMContentLoaded", function () {
            document.querySelectorAll("#mySidebar .nav-link").forEach(function (element) {
                element.addEventListener("click", function (e) {
                    let nextEl = element.nextElementSibling;
                    let parentEl = element.parentElement;

                    if (nextEl) {
                        e.preventDefault();
                        // let mycollapse = new bootstrap.Collapse(nextEl);

                        if (nextEl.classList.contains("show")) {
                            // mycollapse.hide();

                            nextEl.classList.remove("show");
                            // let href = element.getAttribute("href");
                            // window.location.href = href;
                            openLevel(e);
                        }
                        else {
                            nextEl.classList.add("show");
                        }
                    }
                });
            });
        });
    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>