ProSoft.UI/Areas/Accounts/Controllers/AccMainCodeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProSoft.Core.Repositories.Medical.Analysis;
using ProSoft.EF.DTOs.Accounts;
using ProSoft.EF.DTOs.Medical.Analysis;
using ProSoft.EF.IRepositories.Accounts;
using ProSoft.EF.IRepositories.Medical.Analysis;

namespace ProSoft.UI.Areas.Accounts.Controllers
{
    [Authorize]
    [Area(nameof(Accounts))]
    public class AccMainCodeController : Controller
    {
        private readonly IAccMainCodeRepo _accMainCodeRepo;
        private readonly IMapper _mapper;
        public AccMainCodeController(IMapper mapper, IAccMainCodeRepo accMainCodeRepo)
        {
            _accMainCodeRepo = accMainCodeRepo;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.MainLevel_2 = await _accMainCodeRepo.GetMainsByLevelAsync(2);
            ViewBag.MainLevel_3 = await _accMainCodeRepo.GetMainsByLevelAsync(3);
            ViewBag.MainLevel_4 = await _accMainCodeRepo.GetMainsByLevelAsync(4);
            ViewBag.MainLevel_5 = await _accMainCodeRepo.GetMainsByLevelAsync(5);
            return View();
        }
        public async Task<IActionResult> MainLevel_2(string? clickId = "",string? subDeleted= "")
        {
            List<AccMainCodeDTO> mainLevel_2 = await _accMainCodeRepo.GetMainsByLevelAsync(2);

            #region sidebar
            ViewBag.MainLevel_2 = await _accMainCodeRepo.GetMainsByLevelAsync(2);
            ViewBag.MainLevel_3 = await _accMainCodeRepo.GetMainsByLevelAsync(3);
            ViewBag.MainLevel_4 = await _accMainCodeRepo.GetMainsByLevelAsync(4);
            ViewBag.MainLevel_5 = await _accMainCodeRepo.GetMainsByLevelAsync(5);
            #endregion
            ViewBag.clickId = clickId;
            ViewBag.subDeleted = subDeleted;
            return View(mainLevel_2);
        }

        //Get Add
        public async Task<IActionResult> AddMainLevel_2()
        {
            string newMainCode = await _accMainCodeRepo.GetNewMain_2_Async();

            #region sidebar
            ViewBag.MainLevel_2 = await _accMainCodeRepo.GetMainsByLevelAsync(2);
            ViewBag.MainLevel_3 = await _accMainCodeRepo.GetMainsByLevelAsync(3);
            ViewBag.MainLevel_4 = await _accMainCodeRepo.GetMainsByLevelAsync(4);
            ViewBag.MainLevel_5 = await _accMainCodeRepo.GetMainsByLevelAsync(5);
            #endregion

            ViewBag.maincode = newMainCode;
            return View();
        }

        //Post Add
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddMainLevel_2(AccMainCodeEditAddDTO mainDTO)
        {
            if (ModelState.IsValid)
            {
                await _accMainCodeRepo.AddMainLevel_2_Async(mainDTO);
                return RedirectToAction(nameof(MainLevel_2));
            }
            return View(mainDTO);
        }
        //Get Edit
        public async Task<IActionResult> EditMainLevel_2(string id)
        {
            AccMainCodeDTO existingMainCode = await _accMainCodeRepo.GetMainByIdAsync(id);
            AccMainCodeEditAddDTO mappedMainDTO = _mapper.Map<AccMainCodeEditAddDTO>(existingMainCode);

            #region sidebar
            ViewBag.MainLevel_2 = await _accMainCodeRepo.GetMainsByLevelAsync(2);
            ViewBag.MainLevel_3 = await _accMainCodeRepo.GetMainsByLevelAsync(3);
            ViewBag.MainLevel_4 = await _accMainCodeRepo.GetMainsByLevelAsync(4);
            ViewBag.MainLevel_5 = await _accMainCodeRepo.GetMainsByLevelAsync(5);
            #endregion

            return View(mappedMainDTO);
        }

        //Post Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditMainLevel_2(string id, AccMainCodeEditAddDTO mainDTO)
        {
            if (ModelState.IsValid)
            {
                await _accMainCodeRepo.EditMainLevelAsync(id, mainDTO);
                return RedirectToAction(nameof(MainLevel_2));
            }
            return View(mainDTO);
        }

        //Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteMainLevel_2(string id)
        {
            await _accMainCodeRepo.DeleteMainLevelAsync(id);
            return RedirectToAction(nameof(MainLevel_2));
        }

        //////////////////////////////////////////////////////////////////////////////
        //////////////////////////////////////////////////////////////////////////////
        public async Task<IActionResult> MainLevel_3(string? id ="", string? clickId = "", string? subDeleted = "")
        {
            List<AccMainCodeDTO> mainLevel_3 = await _accMainCodeRepo.GetMainsByLevelAsync(3,id);

            #region sidebar
            ViewBag.MainLevel_2 = await _accMainCodeRepo.GetMainsByLevelAsync(2);
            ViewBag.MainLevel_3 = await _accMainCodeRepo.GetMainsByLevelAsync(3, id);
            ViewBag.MainLevel_4 = await _accMainCodeRepo.GetMainsByLevelAsync(4);
            ViewBag.MainLevel_5 = await _accMainCodeRepo.GetMainsByLevelAsync(5);
            #endregion
            ViewBag.main = await _accMainCodeRepo.GetMainByIdAsync(id);
            ViewBag.parent = id;
            ViewBag.clickId = clickId;
            ViewBag.subDeleted = subDeleted;
            return View(mainLevel_3);
        }

        //Get Add
        public async Task<IActionResult> AddMainLevel_3(string parent)
        {
            string newMainCode = await _accMainCodeRepo.GetNewMain_3_Async(parent);

            #region sidebar
            ViewBag.MainLevel_2 = await _accMainCodeRepo.GetMainsByLevelAsync(2);
            ViewBag.MainLevel_3 = await _accMainCodeRepo.GetMainsByLevelAsync(3);
            ViewBag.MainLevel_4 = await _accMainCodeRepo.GetMainsByLevelAsync(4);
            ViewBag.MainLevel_5 = await _accMainCodeRepo.GetMainsByLevelAsync(5);
            #endregion

            ViewBag.maincode = newMainCode;
            ViewBag.CurrentName = (await _accMainCodeRepo.GetMainByIdAsync(parent)).MainName;//for name

            return View();
        }

        //Post Add
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddMainLevel_3(AccMainCodeEditAddDTO mainDTO)
        {
            if (ModelState.IsValid)
            {
                await _accMainCodeRepo.AddMainLevel_3_Async(mainDTO);
                return RedirectToAction(nameof(MainLevel_3), new { id = mainDTO.MainCode});
            }
            return View(mainDTO);
        }
        //Get Edit
        public async Task<IActionResult> EditMainLevel_3(string id)
        {
            AccMainCodeDTO existingMainCode = await _accMainCodeRepo.GetMainByIdAsync(id);
            AccMainCodeEditAddDTO mappedMainDTO = _mapper.Map<AccMainCodeEditAddDTO>(existingMainCode);

            #region sidebar
            ViewBag.MainLevel_2 = await _accMainCodeRepo.GetMainsByLevelAsync(2);
            ViewBag.MainLevel_3 = await _accMainCodeRepo.GetMainsByLevelAsync(3);
            ViewBag.MainLevel_4 = await _accMainCodeRepo.GetMainsByLevelAsync(4);
            ViewBag.MainLevel_5 = await _accMainCodeRepo.GetMainsByLevelAsync(5);
            #endregion

            return View(mappedMainDTO);
        }

        //Post Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditMainLevel_3(string id, AccMainCodeEditAddDTO mainDTO)
        {
            if (ModelState.IsValid)
            {
                await _accMainCodeRepo.EditMainLevelAsync(id, mainDTO);
                return RedirectToAction(nameof(MainLevel_3), new { id = id });
            }
            return View(mainDTO);
        }

        //Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteMainLevel_3(string id)
        {
            await _accMainCodeRepo.DeleteMainLevelAsync(id);
            return RedirectToAction(nameof(MainLevel_2));
        }

        //////////////////////////////////////////////////////////////////////////////
        //////////////////////////////////////////////////////////////////////////////

        public async Task<IActionResult> MainLevel_4(string id, string? clickId = "", string? subDeleted = "")
        {
            List<AccMainCodeDTO> mainLevel_4 = await _accMainCodeRepo.GetMainsByLevelAsync(4);

            #region sidebar
            ViewBag.MainLevel_2 = await _accMainCodeRepo.GetMainsByLevelAsync(2);
            ViewBag.MainLevel_3 = await _accMainCodeRepo.GetMainsByLevelAsync(3);
            ViewBag.MainLevel_4 = await _accMainCodeRepo.GetMainsByLevelAsync(4);
            ViewBag.MainLevel_5 = await _accMainCodeRepo.GetMainsByLevelAsync(5);
            #endregion

            ViewBag.main = await _accMainCodeRepo.GetMainByIdAsync(id);

            string mainString = id.Substring(0, 3); //get main code and substring first 3 digit
            List<AccMainCodeDTO> mains = mainLevel_4
                .Where(obj => obj.MainCode.Substring(0, 3) == mainString).ToList();
            ViewBag.clickId = clickId;
            ViewBag.subDeleted = subDeleted;
            return View(mains);
        }

        //get Add
        public async Task<IActionResult> AddMainLevel_4(string id)
        {
            string newMainCode = await _accMainCodeRepo.GetNewMain_4_Async(id);

            #region sidebar 
            ViewBag.MainLevel_2 = await _accMainCodeRepo.GetMainsByLevelAsync(2);
            ViewBag.MainLevel_3 = await _accMainCodeRepo.GetMainsByLevelAsync(3);
            ViewBag.MainLevel_4 = await _accMainCodeRepo.GetMainsByLevelAsync(4);
            ViewBag.MainLevel_5 = await _accMainCodeRepo.GetMainsByLevelAsync(5);
            #endregion
            ViewBag.parent = id;
            ViewBag.maincode = newMainCode; //display code
            ViewBag.CurrentName = (await _accMainCodeRepo.GetMainByIdAsync(id)).MainName;//for name

            return View();

ProSoft.UI/Areas/Accounts/Views/AccMainCode/AddMainLevel_2.cshtml
@model AccMainCodeEditAddDTO
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Add Voucher";
    Layout = "_LayoutAccounting";
}
@inject IViewLocalizer localizer
@* <style>
    .image {
        top: 0px;
        left: 0px;
        width: 100%;
        height: 100%;
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
        background-position: center;
        opacity: 0.5;
        z-index: -1;
    }
</style> *@
<div class="container pt-2" style="min-height:100vh;">
    @* <img class="image" src="/background.jpg" style="position:absolute;" /> *@

    <div class="d-flex justify-content-between align-items-center mt-3 ">
        <h1>@localizer["Add To Accounts"]</h1>
    </div>

    <form method="post" asp-action="AddMainLevel_2" id="myForm">
        <div class="border p-3 mt-1">

            <div asp-validation-summary="ModelOnly"></div>.
            <!------------------------------------------------------------------------------->

            <div class="parent-permission d-flex align-items-md-end justify-content-center  my-mobile gap-3 ">
                <div class="mb-3">
                    <label asp-for="MainCode"></label>
                    <input asp-for="MainCode" class="form-control" value="@ViewBag.maincode" />
                    <span asp-validation-for="MainCode" class="text-danger"></span>
                </div>
                <div class="mb-3 ">
                    <label asp-for="MainName"></label>
                    <input asp-for="MainName" class="form-control" />
                    <span asp-validation-for="MainName" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="LastLevel"></label>
                    <select asp-for="LastLevel" class="form-control text-center">
                        <option value="0">@localizer["No"]</option>
                        <option value="1"> @localizer["Yes"]</option>
                    </select>
                    <span asp-validation-for="LastLevel" class="text-danger"></span>
                </div>
            </div>
            <!------------------------------------------------------------------------------->

            <div class="parent-permission d-flex align-items-md-end justify-content-center  my-mobile gap-3 ">
                <div class="mb-3">
                    <label asp-for="BalanceFlag"></label>
                    <select asp-for="BalanceFlag" class="form-control text-center">
                        <option value="B"> @localizer["Budget"]</option>
                        <option value="P">@localizer["Profit and Loss"]</option>
                        <option value="N">@localizer["Without"]</option>
                    </select>
                    <span asp-validation-for="BalanceFlag" class="text-danger"></span>
                </div>
                <div class="mb-3 ">
                    <label asp-for="MainSubType"></label>
                    <select asp-for="MainSubType" class="form-control text-center">
                        <option value="mn"> @localizer["Main Balance"]</option>
                        <option value="sb">@localizer["Sub Balance"]</option>
                        <option value="N">@localizer["Without"]</option>
                    </select>
                    <span asp-validation-for="MainSubType" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="OstazType"></label>
                    <select asp-for="OstazType" class="form-control text-center">
                        <option value="mn"> @localizer["Main Balance"]</option>
                        <option value="sb">@localizer["Sub Balance"]</option>
                        <option value="tot">@localizer["The Sum"]</option>
                        <option value="N">@localizer["Without"]</option>
                    </select>
                    <span asp-validation-for="OstazType" class="text-danger"></span>
                </div>
            </div>

            <!------------------------------------------------------------------------------->

            <div class="parent d-flex justify-content-md-center gap-2 ">
                <button type="submit" class="btn btn-primary" style="width:150px">
                    @localizer["Add"]
                </button>
                <a asp-controller="AccMainCode" asp-action="MainLevel_2" class="btn btn-secondary" style="width:150px">
                    @localizer["Cancel"]
                </a>
            </div>
        </div>
    </form>
</div>

ProSoft.UI/Areas/Accounts/Views/AccMainCode/AddMainLevel_3.cshtml
@model AccMainCodeEditAddDTO
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Add Voucher";
    Layout = "_LayoutAccounting";
}
@inject IViewLocalizer localizer
@* <style>
    .image {
        top: 0px;
        left: 0px;
        width: 100%;
        height: 100%;
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
        background-position: center;
        opacity: 0.5;
        z-index: -1;
    }
</style> *@
<div class="container pt-2" style="min-height:100vh;">
    @* <img class="image" src="/background.jpg" style="position:absolute;" /> *@

    <div class="d-flex justify-content-between align-items-center mt-3 ">
        <h1>@localizer["Add To"] @ViewBag.CurrentName</h1>
    </div>

    <form method="post" asp-action="AddMainLevel_3" id="myForm">
        <div class="border p-3 mt-1">

            <div asp-validation-summary="ModelOnly"></div>.
            <!------------------------------------------------------------------------------->

            <div class="parent-permission d-flex align-items-md-end justify-content-center  my-mobile gap-3 ">
                <div class="mb-3">
                    <label asp-for="MainCode"></label>
                    <input asp-for="MainCode" class="form-control" value="@ViewBag.maincode" />
                    <span asp-validation-for="MainCode" class="text-danger"></span>
                </div>
                <div class="mb-3 ">
                    <label asp-for="MainName"></label>
                    <input asp-for="MainName" class="form-control" />
                    <span asp-validation-for="MainName" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="LastLevel"></label>
                    <select asp-for="LastLevel" class="form-control text-center" >
                        <option value="0">@localizer["No"]</option>
                        <option value="1"> @localizer["Yes"]</option>
                    </select>
                    <span asp-validation-for="LastLevel" class="text-danger"></span>
                </div>
            </div>
            <!------------------------------------------------------------------------------->

            <div class="parent-permission d-flex align-items-md-end justify-content-center  my-mobile gap-3 ">
                <div class="mb-3">
                    <label asp-for="BalanceFlag"></label>
                    <select asp-for="BalanceFlag" class="form-control text-center" >
                        <option value="B"> @localizer["Budget"]</option>
                        <option value="P">@localizer["Profit and Loss"]</option>
                        <option value="N">@localizer["Without"]</option>
                    </select>
                    <span asp-validation-for="BalanceFlag" class="text-danger"></span>
                </div>
                <div class="mb-3 ">
                    <label asp-for="MainSubType"></label>
                    <select asp-for="MainSubType" class="form-control text-center" >
                        <option value="mn"> @localizer["Main Balance"]</option>
                        <option value="sb">@localizer["Sub Balance"]</option>
                        <option value="N">@localizer["Without"]</option>
                    </select>
                    <span asp-validation-for="MainSubType" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="OstazType"></label>
                    <select asp-for="OstazType" class="form-control text-center" >
                        <option value="mn"> @localizer["Main Balance"]</option>
                        <option value="sb">@localizer["Sub Balance"]</option>
                        <option value="tot">@localizer["The Sum"]</option>
                        <option value="N">@localizer["Without"]</option>
                    </select>
                    <span asp-validation-for="OstazType" class="text-danger"></span>
                </div>
            </div>

            <!------------------------------------------------------------------------------->

            <div class="parent d-flex justify-content-md-center gap-2 ">
                <button type="submit" class="btn btn-primary" style="width:150px">
                    @localizer["Add"]
                </button>
                <a asp-controller="AccMainCode" asp-action="MainLevel_2" class="btn btn-secondary" style="width:150px">
                    @localizer["Cancel"]
                </a>
            </div>
        </div>
    </form>
</div>

ProSoft.UI/Areas/Accounts/Views/AccMainCode/AddMainLevel_4.cshtml
@model AccMainCodeEditAddDTO
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Add Voucher";
    Layout = "_LayoutAccounting";
}
@inject IViewLocalizer localizer
@* <style>
    .image {
        top: 0px;
        left: 0px;
        width: 100%;
        height: 100%;
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
        background-position: center;
        opacity: 0.5;
        z-index: -1;
    }
</style> *@
<div class="container pt-2" style="min-height:100vh;">
    @* <img class="image" src="/background.jpg" style="position:absolute;" /> *@

    <div class="d-flex justify-content-between align-items-center mt-3 ">
        <h1>@localizer["Add To"] @ViewBag.CurrentName</h1>
    </div>

    <form method="post" asp-action="AddMainLevel_4" id="myForm">
        <div class="border p-3 mt-1">

            <div asp-validation-summary="ModelOnly"></div>.
            <!------------------------------------------------------------------------------->

            <div class="parent-permission d-flex align-items-md-end justify-content-center  my-mobile gap-3 ">
                <div class="mb-3">
                    <label asp-for="MainCode"></label>
                    <input asp-for="MainCode" class="form-control" value="@ViewBag.maincode" />
                    <span asp-validation-for="MainCode" class="text-danger"></span>
                </div>
                <div class="mb-3 ">
                    <label asp-for="MainName"></label>
                    <input asp-for="MainName" class="form-control" />
                    <span asp-validation-for="MainName" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="LastLevel"></label>
                    <select asp-for="LastLevel" class="form-control text-center" >
                        <option value="0">@localizer["No"]</option>
                        <option value="1"> @localizer["Yes"]</option>
                    </select>
                    <span asp-validation-for="LastLevel" class="text-danger"></span>
                </div>
            </div>
            <!------------------------------------------------------------------------------->

            <div class="parent-permission d-flex align-items-md-end justify-content-center  my-mobile gap-3 ">
                <div class="mb-3">
                    <label asp-for="BalanceFlag"></label>
                    <select asp-for="BalanceFlag" class="form-control text-center" >
                        <option value="B"> @localizer["Budget"]</option>
                        <option value="P">@localizer["Profit and Loss"]</option>
                        <option value="N">@localizer["Without"]</option>
                    </select>
                    <span asp-validation-for="BalanceFlag" class="text-danger"></span>
                </div>
                <div class="mb-3 ">
                    <label asp-for="MainSubType"></label>
                    <select asp-for="MainSubType" class="form-control text-center" >
                        <option value="mn"> @localizer["Main Balance"]</option>
                        <option value="sb">@localizer["Sub Balance"]</option>
                        <option value="N">@localizer["Without"]</option>
                    </select>
                    <span asp-validation-for="MainSubType" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="OstazType"></label>
                    <select asp-for="OstazType" class="form-control text-center" >
                        <option value="mn"> @localizer["Main Balance"]</option>
                        <option value="sb">@localizer["Sub Balance"]</option>
                        <option value="tot">@localizer["The Sum"]</option>
                        <option value="N">@localizer["Without"]</option>
                    </select>
                    <span asp-validation-for="OstazType" class="text-danger"></span>
                </div>
            </div>

            <!------------------------------------------------------------------------------->

            <div class="parent d-flex justify-content-md-center gap-2 ">
                <button type="submit" class="btn btn-primary" style="width:150px">
                    @localizer["Add"]
                </button>
                <a asp-controller="AccMainCode" asp-action="MainLevel_4" asp-route-id="@ViewBag.parent" class="btn btn-secondary" style="width:150px">
                    @localizer["Cancel"]
                </a>
            </div>
        </div>
    </form>
</div>

ProSoft.UI/Areas/Accounts/Views/AccMainCode/AddMainLevel_5.cshtml
@model AccMainCodeEditAddDTO
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Add Voucher";
    Layout = "_LayoutAccounting";
}
@inject IViewLocalizer localizer
@* <style>
    .image {
        top: 0px;
        left: 0px;
        width: 100%;
        height: 100%;
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
        background-position: center;
        opacity: 0.5;
        z-index: -1;
    }
</style> *@
<div class="container pt-2" style="min-height:100vh;">
    @* <img class="image" src="/background.jpg" style="position:absolute;" /> *@

    <div class="d-flex justify-content-between align-items-center mt-3 ">
        <h1>@localizer["Add To"] @ViewBag.CurrentName</h1>
    </div>

    <form method="post" asp-action="AddMainLevel_5" id="myForm">
        <div class="border p-3 mt-1">

            <div asp-validation-summary="ModelOnly"></div>.
            <!------------------------------------------------------------------------------->

            <div class="parent-permission d-flex align-items-md-end justify-content-center  my-mobile gap-3 ">
                <div class="mb-3">
                    <label asp-for="MainCode"></label>
                    <input asp-for="MainCode" class="form-control" value="@ViewBag.maincode" />
                    <span asp-validation-for="MainCode" class="text-danger"></span>
                </div>
                <div class="mb-3 ">
                    <label asp-for="MainName"></label>
                    <input asp-for="MainName" class="form-control" />
                    <span asp-validation-for="MainName" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="LastLevel"></label>
                    <select asp-for="LastLevel" class="form-control text-center" >
                        <option value="0">@localizer["No"]</option>
                        <option value="1"> @localizer["Yes"]</option>
                    </select>
                    <span asp-validation-for="LastLevel" class="text-danger"></span>
                </div>
            </div>
            <!------------------------------------------------------------------------------->

            <div class="parent-permission d-flex align-items-md-end justify-content-center  my-mobile gap-3 ">
                <div class="mb-3">
                    <label asp-for="BalanceFlag"></label>
                    <select asp-for="BalanceFlag" class="form-control text-center" >
                        <option value="B"> @localizer["Budget"]</option>
                        <option value="P">@localizer["Profit and Loss"]</option>
                        <option value="N">@localizer["Without"]</option>
                    </select>
                    <span asp-validation-for="BalanceFlag" class="text-danger"></span>
                </div>
                <div class="mb-3 ">
                    <label asp-for="MainSubType"></label>
                    <select asp-for="MainSubType" class="form-control text-center" >
                        <option value="mn"> @localizer["Main Balance"]</option>
                        <option value="sb">@localizer["Sub Balance"]</option>
                        <option value="N">@localizer["Without"]</option>
                    </select>
                    <span asp-validation-for="MainSubType" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="OstazType"></label>
                    <select asp-for="OstazType" class="form-control text-center" >
                        <option value="mn"> @localizer["Main Balance"]</option>
                        <option value="sb">@localizer["Sub Balance"]</option>
                        <option value="tot">@localizer["The Sum"]</option>
                        <option value="N">@localizer["Without"]</option>
                    </select>
                    <span asp-validation-for="OstazType" class="text-danger"></span>
                </div>
            </div>

            <!------------------------------------------------------------------------------->

            <div class="parent d-flex justify-content-md-center gap-2 ">
                <button type="submit" class="btn btn-primary" style="width:150px">
                    @localizer["Add"]
                </button>
                <a asp-controller="AccMainCode" asp-action="MainLevel_5" asp-route-id="@ViewBag.parent" class="btn btn-secondary" style="width:150px">
                    @localizer["Cancel"]
                </a>
            </div>
        </div>
    </form>
</div>

ProSoft.UI/Areas/Accounts/Views/AccMainCode/Index.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{

    Layout = "_LayoutAccounting";

}
@inject IViewLocalizer localizer
<div class="container pt-2 ">
    <h2 class="mt-4">@localizer["Accounts"]</h2>
</div>