ProSoft.UI/Areas/Treasury/Controllers/UserCashNoController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProSoft.Core.Repositories;
using ProSoft.Core.Repositories.Treasury;
using ProSoft.EF.DTOs.Auth;
using ProSoft.EF.DTOs.Stocks;
using ProSoft.EF.DTOs.Treasury;
using ProSoft.EF.IRepositories;
using ProSoft.EF.IRepositories.Treasury;
using ProSoft.EF.Models;
using ProSoft.EF.Models.Accounts;
using ProSoft.EF.Models.Stocks;
using ProSoft.EF.Models.Treasury;

namespace ProSoft.UI.Areas.Treasury.Controllers
{
    [Authorize]
    [Area(nameof(Treasury))]
    public class UserCashNoController : Controller
    {
        private readonly IUserCashNoRepo _userCashNoRepo;
        private readonly IUserRepo _userRepo;
        private readonly IMapper _mapper;
        public UserCashNoController(IUserCashNoRepo userCashNoRepo, IUserRepo userRepo, IMapper mapper)
        {
            _userCashNoRepo = userCashNoRepo;
            _userRepo = userRepo;
            _mapper = mapper;
        }
        public async Task<IActionResult> Index(int? redirect)
        {
            List<AppUser> users = await _userRepo.GetAllUsersAsync();
            List<UserDTO> usersDTO = _mapper.Map<List<UserDTO>>(users);
            ViewBag.redirect = redirect;
            return View(usersDTO);
        }

        //Ajax In Index
        public async Task<IActionResult> GetSafeTransForUser(int id)
        {
            List<UserCashNoViewDTO> userCashNoDTOs = await _userCashNoRepo
                .GetCashForUserAsync(id);
            return Json(userCashNoDTOs);
        }

        // Get Add
        public async Task<IActionResult> Add_UserCashNo(int id)
        {
            ViewBag.userName = (await _userRepo.GetUserByIdAsync(id)).UserName;
            UserCashNoEditAddDTO userCashNoDTO = await _userCashNoRepo.GetEmptySafeTransAsync(id);
            return View(userCashNoDTO);
        }

        //// Post Add
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add_UserCashNo(int id, UserCashNoEditAddDTO userCashNoDTO)
        {
            if (ModelState.IsValid)
            {
                userCashNoDTO.BranchId = int.Parse(User.Claims.FirstOrDefault(c => c.Type == "U_Branch_Id").Value);
                userCashNoDTO.UserCode = id;

                await _userCashNoRepo.AddSafeTransAsync(userCashNoDTO);
                return RedirectToAction(nameof(Index), new { redirect = id });
            }
            return View(userCashNoDTO);
        }

        // Get Edit
        public async Task<IActionResult> Edit_UserCashNo(int id)
        {
            UserCashNoEditAddDTO userCashNoDTO = await _userCashNoRepo.GetSafeTransByIdAsync(id);
            ViewBag.subAccCodesSub = await _userCashNoRepo.GetSubCodesFromAccAsync(userCashNoDTO.MainCode);
            ViewBag.subAccCodesMain = await _userCashNoRepo.GetSubCodesFromAccAsync(userCashNoDTO.MainCode2);
            ViewBag.userName = (await _userRepo.GetUserByIdAsync(userCashNoDTO.UserCode)).UserName;

            return View(userCashNoDTO);
        }

        // Post Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit_UserCashNo(int id, UserCashNoEditAddDTO userCashNoDTO)
        {
            if (ModelState.IsValid)
            {
                userCashNoDTO.BranchId = int.Parse(User.Claims.FirstOrDefault(c => c.Type == "U_Branch_Id").Value);

                await _userCashNoRepo.EditSafeTransAsync(id, userCashNoDTO);
                return RedirectToAction(nameof(Index), new { redirect = userCashNoDTO.UserCode });
            }
            return View(userCashNoDTO);
        }

        // Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete_UserCashNo(int id)
        {
            UserCashNo userCashNo = await _userCashNoRepo.GetByIdAsync(id);

            await _userCashNoRepo.DeleteAsync(userCashNo);
            await _userCashNoRepo.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { redirect = userCashNo.UserCode });
        }
    }
}

ProSoft.UI/Areas/Treasury/Views/UserCashNo/Add_UserCashNo.cshtml
@model UserCashNoEditAddDTO
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Add New Transaction";
    Layout = "_Layout";

    // Casting type to get all Stocks as a list
    SelectList stocks = new SelectList(Model.treasuryNames, "SafeCode", "SafeNames");

    // Casting type to get all MainAccCodes as a list
    SelectList mainAccCodes = new SelectList(Model.MainAccCodes, "MainCode", "MainName");
}
@inject IViewLocalizer localizer

<div class="container pt-2">
    <h1 class="mt-4">@localizer["Add New SafeTransaction For User"] : @ViewBag.userName</h1>
    <form method="post" asp-action="Add_StockTrans">
        <div class="border p-3 mt-4">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="parent d-flex align-items-md-end justify-content-center gap-md-3 my-mobile ">
                <div class="mb-3">
                    <label asp-for="SafeCode"></label>
                    <select asp-for="SafeCode" asp-items="stocks" class="form-control text-center">
                        <option value="">-- Choose --</option>
                    </select>
                    <span asp-validation-for="SafeCode" class="text-danger"></span>
                </div>
                <div class="mb-3 d-flex justify-content-center gap-2">
                   <div style="width: 50%;">
                        <label asp-for="ActdeactFlag"></label>
                        <select asp-for="ActdeactFlag" class="form-control text-center">
                            <option value="1">@localizer["Yes"]</option>
                            <option value="0">@localizer["No"]</option>
                        </select>
                        <span asp-validation-for="ActdeactFlag" class="text-danger"></span>
                   </div>
                   <div style="width: 50%;">
                        <label asp-for="CshUsr"></label>
                        <select asp-for="CshUsr" class="form-control text-center">
                            <option value="N">@localizer["No"]</option>
                            <option value="Y">@localizer["Yes"]</option>
                        </select>
                        <span asp-validation-for="CshUsr" class="text-danger"></span>
                   </div>
                </div>
            </div>

            <!------------------------------------------------------------------------------->

            <div class="parent d-flex align-items-md-start justify-content-center gap-md-3 my-mobile ">
                <div class="mb-3">
                    <label asp-for="MainCode"></label>
                    <select asp-for="MainCode" asp-items="mainAccCodes" class="form-control text-center" onchange="getSubCodes('MainCode', 'SubCode')">
                        <option value="">-- Choose --</option>
                    </select>
                    <span asp-validation-for="MainCode" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="SubCode"></label>
                    <select asp-for="SubCode" class="form-control text-center">
                        <option value="">-- Choose --</option>
                    </select>
                    <span asp-validation-for="SubCode" class="text-danger"></span>
                </div>
            </div>
           
            <!------------------------------------------------------------------------------->
            <div class="d-flex justify-content-center fw-bold"><p>@localizer["Convert To"]</p></div>
            <!------------------------------------------------------------------------------->
            
            <div class="parent d-flex align-items-md-start justify-content-center gap-md-3 my-mobile ">
                <div class="mb-3">
                    <label asp-for="MainCode2"></label>
                    <select asp-for="MainCode2" asp-items="mainAccCodes" class="form-control text-center" onchange="getSubCodes('MainCode2', 'SubCode2')">
                        <option value="">-- Choose --</option>
                    </select>
                    <span asp-validation-for="MainCode2" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="SubCode2"></label>
                    <select asp-for="SubCode2" class="form-control text-center">
                        <option value="">-- Choose --</option>
                    </select>
                    <span asp-validation-for="SubCode2" class="text-danger"></span>
                </div>
            </div>
           
            <!------------------------------------------------------------------------------->

            <div class="parent d-flex justify-content-md-center gap-2">
                <button type="submit" class="btn btn-primary" style="width:150px">@localizer["Add"]</button>
                <a asp-controller="UserCashNo" asp-action="Index" class="btn btn-secondary" style="width:150px">
                    @localizer["Cancel"]
                </a>
            </div>
        </div>
    </form>
</div>

<script>

    function getSubCodes(mainId, subId){
        let mainElement = document.getElementById(mainId);
        let subElement = document.getElementById(subId);
        subElement.innerHTML = `<option value="">-- Choose --</option>`;

        $.ajax({
            url: `/Stocks/UserStockTransaction/GetSubCodesFromAcc/${mainElement.value}`,
            success: function (result) {
                console.log(result);
                for (let item of result) {
                    subElement.innerHTML +=
                        `<option value="${item.subCode}">${item.subName}</option>`;
                }
            }
        });
    }
</script>

ProSoft.UI/Areas/Treasury/Views/UserCashNo/Edit_UserCashNo.cshtml
@model UserCashNoEditAddDTO
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Add New Transaction";
    Layout = "_Layout";

    // Casting type to get all Stocks as a list
    SelectList stocks = new SelectList(Model.treasuryNames, "SafeCode", "SafeNames");

    // Casting type to get all MainAccCodes as a list
    SelectList mainAccCodes = new SelectList(Model.MainAccCodes, "MainCode", "MainName");

    // Casting type to get all SubAccCodes_Stk as a list
    SelectList subAccCodes_Sub = new SelectList(ViewBag.subAccCodesSub, "SubCode", "SubName");

    // Casting type to get all SubAccCodes_Acc as a list
    SelectList subAccCodes_Main = new SelectList(ViewBag.subAccCodesMain, "SubCode", "SubName");
}
@inject IViewLocalizer localizer

<div class="container pt-2">
    <h1 class="mt-4">@localizer["Edit New SafeTransaction For User"] : @ViewBag.userName</h1>
    <form method="post" asp-action="Edit_UserCashNo">
        <div class="border p-3 mt-4">
            @* Hidden *@
            <input asp-for="UserCashID" type="hidden" />
            <input asp-for="UserCode" type="hidden" />

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="parent d-flex align-items-md-end justify-content-center gap-md-3 my-mobile ">
                <div class="mb-3">
                    <label asp-for="SafeCode"></label>
                    <select asp-for="SafeCode" asp-items="stocks" class="form-control text-center">
                        <option value="">-- Choose --</option>
                    </select>
                    <span asp-validation-for="SafeCode" class="text-danger"></span>
                </div>
                <div class="mb-3 d-flex justify-content-center gap-2">
                    <div style="width: 50%;">
                        <label asp-for="ActdeactFlag"></label>
                        <select asp-for="ActdeactFlag" class="form-control text-center">
                            <option value="1">@localizer["Yes"]</option>
                            <option value="0">@localizer["No"]</option>
                        </select>
                        <span asp-validation-for="ActdeactFlag" class="text-danger"></span>
                    </div>
                    <div style="width: 50%;">
                        <label asp-for="CshUsr"></label>
                        <select asp-for="CshUsr" class="form-control text-center">
                            <option value="N">@localizer["No"]</option>
                            <option value="Y">@localizer["Yes"]</option>
                        </select>
                        <span asp-validation-for="CshUsr" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <!------------------------------------------------------------------------------->

            <div class="parent d-flex align-items-md-start justify-content-center gap-md-3 my-mobile ">
                <div class="mb-3">
                    <label asp-for="MainCode"></label>
                    <select asp-for="MainCode" asp-items="mainAccCodes" class="form-control text-center" onchange="getSubCodes('MainCode', 'SubCode')">
                        <option value="">-- Choose --</option>
                    </select>
                    <span asp-validation-for="MainCode" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="SubCode"></label>
                    <select asp-for="SubCode" asp-items="subAccCodes_Sub" class="form-control text-center">
                        <option value="">-- Choose --</option>
                    </select>
                    <span asp-validation-for="SubCode" class="text-danger"></span>
                </div>
            </div>

            <!------------------------------------------------------------------------------->
            <div class="d-flex justify-content-center fw-bold"><p>@localizer["Convert To"]</p></div>
            <!------------------------------------------------------------------------------->

            <div class="parent d-flex align-items-md-start justify-content-center gap-md-3 my-mobile ">
                <div class="mb-3">
                    <label asp-for="MainCode2"></label>
                    <select asp-for="MainCode2" asp-items="mainAccCodes" class="form-control text-center" onchange="getSubCodes('MainCode2', 'SubCode2')">
                        <option value="">-- Choose --</option>
                    </select>
                    <span asp-validation-for="MainCode2" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="SubCode2"></label>
                    <select asp-for="SubCode2" asp-items="subAccCodes_Main" class="form-control text-center">
                        <option value="">-- Choose --</option>
                    </select>
                    <span asp-validation-for="SubCode2" class="text-danger"></span>
                </div>
            </div>

            <!------------------------------------------------------------------------------->

            <div class="parent d-flex justify-content-md-center gap-2">
                <button type="submit" class="btn btn-success" style="width:150px">@localizer["Save Changes"]</button>
                <a asp-controller="UserCashNo" asp-action="Index" class="btn btn-secondary" style="width:150px">
                    @localizer["Cancel"]
                </a>
            </div>
        </div>
    </form>
</div>

<script>

    function getSubCodes(mainId, subId) {
        let mainElement = document.getElementById(mainId);
        let subElement = document.getElementById(subId);
        subElement.innerHTML = `<option value="">-- Choose --</option>`;

        $.ajax({
            url: `/Stocks/UserStockTransaction/GetSubCodesFromAcc/${mainElement.value}`,
            success: function (result) {
                console.log(result);
                for (let item of result) {
                    subElement.innerHTML +=
                        `<option value="${item.subCode}">${item.subName}</option>`;
                }
            }
        });
    }
</script>

ProSoft.UI/Areas/Treasury/Views/UserCashNo/Index.cshtml
@using ProSoft.UI.Global
@model List<UserDTO>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Joining Users With Treasurys";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@inject IViewLocalizer localizer

<div class="text-center">
    <h1 class="mb-2">@localizer["Joining Users With Treasurys"] </h1>
    <input id="redirect" type="hidden" value="@ViewBag.redirect" />

</div>

<div class="container pt-2" style=" min-height:100vh;">
    <div class="d-flex justify-content-between align-items-center flex-column flex-md-row my-2">
        <div style="width: 40%;">
            <input type="text" id="searchInput" class="form-control" oninput="searchUsers(event)" placeholder="@localizer["Search users by user code or name ..."]">
        </div>
    </div>
    <div class="overflow-auto" style="height: 225px;">
        <table id="myTable" class="table table-bordered table-hover" style="width:100%;">
            <thead class="table-dark">
                <tr>
                    <th class="align-middle">
                        @localizer["Code"]
                    </th>
                    <th class="align-middle" style="min-width: 150px;">
                        @localizer["User Name"]
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr onclick="getSafeTransactions(event, @item.UserCode)" style="cursor:pointer;">
                        <td class="align-middle">@item.UserCode</td>
                        <td class="align-middle user-name">@item.UserName</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    @* /////////////////////////////////////////////////////////////////// *@

    @* Table for UserSafe Transactions *@

    <div class="transactions-table-head d-flex justify-content-between align-items-center mt-3 mb-1">
        <h2 class="header">@localizer["Transactions of Safes for User"] :</h2>
        <a class="btn btn-sm btn-primary fs-6">
            @Html.Raw(GlobalConstants.InsertIcon) @localizer["Add New Transaction"]
        </a>
    </div>

    <div class="p-0 mb-2 border-opacity-75 overflow-auto" style="max-height: 300px;">

        <table id="myTable_2" class="table table-bordered table-hover" style="width:100%">
            <thead class="table-dark">
                <tr class="align-middle">
                    <th>
                        @localizer["Serial"]
                    </th>
                    <th>
                        @localizer["Treasury"]
                    </th>
                    <th>
                        @localizer["Posting To Safes"]
                    </th>
                    <th class="text-center">
                        @localizer["Activation"]
                    </th>
                    <th>
                        @localizer["Sub Safe Treasury"]
                    </th>
                    <th>
                        @localizer["Main Safe Treasury"]
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>

@section Scripts {
    <script>
        function searchUsers(e) {
            let input = e.target;
            let filterValue = input.value.toLowerCase();
            let rows = document.querySelectorAll("#myTable tbody tr");

            if (!filterValue) {
                for (let i = 0, len = rows.length; i < len; i++) {
                    rows[i].style.display = "";
                }
                return;
            }
            // Loop through all table rows, hide those that do not match the search query
            for (let i = 0, len1 = rows.length; i < len1; i++) {
                let elements = rows[i].querySelectorAll("td");
                for (let j = 0, len2 = elements.length; j < len2; j++) {
                    let td = elements[j];
                    if (td) {
                        let tdValue = td.textContent || td.innerText;
                        tdValue = tdValue.toLowerCase();
                        if (tdValue.indexOf(filterValue) > -1) {
                            rows[i].style.display = "";
                            break;
                        } else {
                            rows[i].style.display = "none";
                        }
                    }
                }
            }
        }

        function getSafeTransactions(e, userCode) {
            // Handle active click
            let allItemRows = e.target.parentElement.parentElement.querySelectorAll("tr");;
            let clickedTarget = e.target.parentElement;

            ///////////////////////////////////////////////////////////////////
            let userTransactions = document.querySelector("#myTable_2 tbody");
            let transactionsHead = document.querySelector(".transactions-table-head");
            let transactionsHeader = transactionsHead.querySelector(".header");
            let transAddLink = transactionsHead.querySelector("a");

            ///////////////////////////////////////////////////////////////////
            // if (transType) {
            allItemRows.forEach(row => {
                row.classList.remove("active-row");
            });
            clickedTarget.classList.add("active-row");

            let userName = clickedTarget.querySelector(".user-name").innerText;
            transactionsHeader.innerHTML = `@localizer["Transactions of Safes for User"] : ${userName}`;

            transAddLink.setAttribute("href", `/Treasury/UserCashNo/Add_UserCashNo/${userCode}`);

            userTransactions.innerHTML = "";  // Empty the table

            $.ajax({
                url: `/Treasury/UserCashNo/GetSafeTransForUser/${userCode}`,
                success: function (result) {
                  //  console.log(result);
                  //to disable l add when user has Treasury
                    let count = 0;
                    if (result.length > 0) {
                        transAddLink.classList.add("btn-secondary");
                        transAddLink.style.pointerEvents = "none";
                    }
                    else {
                        transAddLink.classList.remove("btn-secondary");
                        transAddLink.style.pointerEvents = "all";
                    }
                    for (let item of result) {
                        count++;
                        let actdeactFlag = item.actdeactFlag == 1 ? `<i class="fa-solid fa-check"></i>` : "";
                        let cshUsr = item.cshUsr == 'Y' ? `<i class="fa-solid fa-check"></i>` : "";

                        const userTrans = document.createElement("tr");
                        userTrans.innerHTML =
                            `
                                    <td class="align-middle text-center">${count}</td>
                                    <td class="align-middle text-center">${item.safeNames}</td>
                                    <td class="align-middle text-center">${actdeactFlag}</td>
                                    <td class="align-middle text-center">${cshUsr}</td>
                                    <td class="align-middle text-center">${item.safeSub}</td>
                                    <td class="align-middle text-center">${item.safeMain}</td>
                                    <td class="text-center align-middle">
                                    <a href="/Treasury/UserCashNo/Edit_UserCashNo/${item.userCashID}" class="btn btn-sm btn-warning mb-1 fs-6">@Html.Raw(GlobalConstants.EditIcon)</a>
                                    <form action="/Treasury/UserCashNo/Delete_UserCashNo" method="post" class="d-inline">
        @Html.AntiForgeryToken()
                                            <input type="hidden" name="id" value="${item.userCashID}" />
                                        <button type="button" onclick="openModalListener(event)" class="btn btn-sm btn-danger mb-1  fs-6" data-modal-target>@Html.Raw(GlobalConstants.DeleteIcon)</button>
                                        <div class="modal-container">
                                            <div class="modal 4" id="modal">
                                                <div class="modal-header fs-4">
                                                    <div class="title">@localizer["Confirm Delete"]</div>
                                                    <button type="button" onclick="closeModelListener(event)" data-close-button class="close-button">&times;</button>
                                                </div>
                                                        <div class="modal-body fs-4">
        @localizer["Are you sure you want to delete this item ?"]
                                                </div>
                                                        <div class="modal-footer fs-4">
                                                    <button type="button" onclick="closeModelListener(event)" data-close-button class="btn btn-secondary">@localizer["No"]</button>
                                                    <button class="btn btn-danger">@localizer["Yes"]</button>
                                                </div>
                                            </div>
                                            <div onclick="overlayListener(event)" id="overlay"></div>
                                        </div>
                                        </form>
                                    </td>
                                    `;
                        userTransactions.appendChild(userTrans);
                    }
                }
            });
        }

        (function autoClick() {
            let redirectNum = document.getElementById("redirect").value;
            let rows = document.querySelectorAll("#myTable tbody tr");

            if (redirectNum === null || redirectNum == 0) {
                // If redirectNum is null or 0, click the first row
                if (rows.length > 0) {
                    rows[0].querySelector("td:first-child").click();
                }
            } else {
                // Loop through all table rows to find and click the one that matches redirectNum
                for (let i = 0, len1 = rows.length; i < len1; i++) {
                    let firstTd = rows[i].querySelector("td:first-child");  // Select the first td in the row
                    if (firstTd) {
                        let tdValue = firstTd.textContent || firstTd.innerText;
                        tdValue = tdValue.toLowerCase();
                        if (tdValue.indexOf(redirectNum) > -1) {  // Compare with redirectNum
                            firstTd.click();
                            break;
                        }
                    }
                }
            }
        })();
    </script>
}